# output/mappings
# ├── ai_mappings_intersection_matches.csv
# ├── ai_mappings_unique_not_in_intersection_matches.csv
# ├── edam_exact_synonym_fbbi_exact_synonym_matches.csv
# ├── edam_exact_synonym_fbbi_label_matches.csv
# ├── edam_fbbi_label_matches.csv
# └── edam_label_fbbi_exact_synonym_matches.csv

import pandas as pd

# Load the results from the 10 runs and fill in a SSSOM mapping file with union of all matches

# subject_id
# subject_label
# predicate_id = skos:exactMatch
# object_id
# object_label
# mapping_justification = semapv:UnspecifiedMatching for ai, semapv:LexicalMatching for other matches
# author_id = 0000-0003-2473-2313
# confidence
# comment = "generated by DeepSeek-V3.2, in 10/10 runs" or
# "generated by DeepSeev-V3.2 in at least 1/10 runs" or
# "exact match ... details if label / synonym and where"
global_metadata = {
    "author_id": "0000-0003-2473-2313",
    "license": "https://creativecommons.org/publicdomain/zero/1.0/",
}
metadata = [
    {
        "file_name": "ai_mappings_intersection_matches.csv",
        "mapping_justification": "semapv:UnspecifiedMatching",
        "confidence": 0.7,
        "comment": "generated by DeepSeek-V3.2, in 10/10 runs",
    },
    {
        "file_name": "ai_mappings_unique_not_in_intersection_matches.csv",
        "mapping_justification": "semapv:UnspecifiedMatching",
        "confidence": 0.6,
        "comment": "generated by DeepSeek-V3.2 in at least 1/10 runs",
    },
    {
        "file_name": "edam_exact_synonym_fbbi_exact_synonym_matches.csv",
        "mapping_justification": "semapv:LexicalMatching",
        "confidence": 0.9,
        "comment": "exact match between EDAM exact synonym and FBbi exact synonym",
    },
    {
        "file_name": "edam_exact_synonym_fbbi_label_matches.csv",
        "mapping_justification": "semapv:LexicalMatching",
        "confidence": 0.8,
        "comment": "exact match between EDAM exact synonym and FBbi label",
    },
    {
        "file_name": "edam_label_fbbi_exact_synonym_matches.csv",
        "mapping_justification": "semapv:LexicalMatching",
        "confidence": 0.9,  # I trust more exact synonyms in FBbi than EDAM at this point (subjective)
        "comment": "exact match between EDAM label and FBbi exact synonym",
    },
    {
        "file_name": "edam_fbbi_label_matches.csv",
        "mapping_justification": "semapv:LexicalMatching",
        "confidence": 1.0,
        "comment": "exact match between EDAM label and FBbi label (case-insensitive)",
    },
]

dfs = []
for metadata_entry in metadata:
    df = pd.read_csv(f"output/mappings/{metadata_entry['file_name']}")
    new_df = df[["edam_id", "edam_label", "fbbi_id", "fbbi_label"]]
    new_df.rename(
        columns={
            "edam_id": "subject_id",
            "edam_label": "subject_label",
            "fbbi_id": "object_id",
            "fbbi_label": "object_label",
        },
        inplace=True,
    )
    new_df["predicate_id"] = "skos:exactMatch"
    new_df["mapping_justification"] = metadata_entry["mapping_justification"]
    new_df["confidence"] = metadata_entry["confidence"]
    new_df["comment"] = metadata_entry["comment"]
    new_df["author_id"] = global_metadata["author_id"]
    dfs.append(df)

# Combine all dataframes into one

# TODO: clean up overlaps between different methods
# e.g. if a match is found by both label and exact synonym,
# keep only one entry with the highest confidence and most specific mapping justification
# (e.g. LexicalMatching over UnspecifiedMatching)
combined_df = pd.concat([df for df in dfs], ignore_index=True)

combined_df.to_csv("output/edam_fbbi_mappings_sssom.tsv", sep="\t", index=False)
